// export const API_BASE = 'https://powerful-earth-40118.herokuapp.com';
export const API_BASE = 'http://localhost:8000'; // for testing when offline
export const ACKNOWLEDGE_ERROR_MESSAGE = 'ACKNOWLEDGE_ERROR_MESSAGE';
export const RECEIVE_ERROR_MESSAGE = 'RECEIVE_ERROR_MESSAGE';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const RECIVE_AUTH_UPDATE = 'RECIVE_AUTH_UPDATE';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const RECEIVE_USER_DISTRICT_INFO = 'RECEIVE_USER_DISTRICT_INFO';
export const VERIFY_USER_DISTRICT_INF0 = 'VERIFY_USER_DISTRICT_INF0';
export const RECEIVE_USER_REPS = 'RECEIVE_USER_REPS';
export const RECEIVE_FLOOR_ITEMS = 'RECEIVE_FLOOR_ITEMS';
