export const testReps = {
  F000062 : {
    api_uri : "https://api.propublica.org/congress/v1/members/F000062.json",
    gender : "F",
    id : "F000062",
    name : "Dianne Feinstein",
    next_election : "2018",
    party : "D",
    role : "Senator, 1st Class",
    seniority : "25",
    times_topics_url : "http://topics.nytimes.com/top/reference/timestopics/people/f/dianne_feinstein/index.html",
    twitter_id : "SenFeinstein",
    youtube_id : "SenatorFeinstein",
  },
  H001075 : {
    api_uri : "https://api.propublica.org/congress/v1/members/H001075.json",
    gender : "F",
    id : "H001075",
    name : "Kamala Harris",
    next_election : "2022",
    party : "D",
    role : "Senator, 3rd Class",
    seniority : "1",
    times_topics_url : "",
    twitter_id : "SenKamalaHarris",
    youtube_id : "",
  },
  S001193: {
    api_uri : "https://api.propublica.org/congress/v1/members/S001193.json",
    district : "15",
    gender : "M",
    id : "S001193",
    name : "Eric Swalwell",
    next_election : "2018",
    party : "D",
    role : "Representative",
    seniority : "6",
    times_topics_url : "",
    twitter_id : "RepSwalwell",
    youtube_id : "ericswalwell",
  }
};
